16. 本の投稿ができない: 投稿するとparam is missing or the value is empty: book 17. 本の投稿ができない: エラーメッセージが表示されない 18. 本の投稿ができない: データが保存できない 19. NameError in Books#show, undefined local variable or method 'user' 20. NoMethodError in Books#show, undefined method 'get_profile_image' for #<user::activerecord_associations_collectionproxy:xxxxx> 21. 本の詳細ページで新規投稿フォームが編集フォームになっている 22. 本の投稿が削除できない 23. introductionカラムにバリデーションが設定されていない 24. 他ユーザーのプロフィールを編集できないようにする 25. 他ユーザーが投稿した本の編集、削除のリンクを表示させない 26. 本の更新失敗時にもエラー文が表示されない 27. ログイン中にURLを入力すると他人が投稿した本の編集ページに遷移できないようにする